### ISSUE TITLE
Suddenly not working

### ISSUE THREAD

**Issue by lansotto** [fmeum/ics2gcal#6]
The extension icon is greyed out and flashes blue temporarily when clicked on.  I also don't see the the usual option to add to a specific calendar when I right click on an ICS file.  Been using this extension for months so this is new.  Please help.

**Comment by dvismans** [comment]
Same issue for me, just installed the extension but clicking it doesn't do anything so can't set the calendar I want to add to.

**Comment by meatballSuzy** [comment]
And me, this issue hasn't been fixed. As you can't click on Options it means the whole app doesn't work as you can't direct to the correct calendar.
