### ISSUE TITLE
Error with download link

### ISSUE THREAD

**Issue by smnjhull** [fmeum/ics2gcal#8]
<img width="947" alt="error" src="https://user-images.githubusercontent.com/29181250/109674680-1b8b3580-7b45-11eb-8fbf-6cecb200078b.png">
When attempting to add an event to a calendar using a download file (link) button by right-clicking on the button (link) the appropriate action window appears and selection of calendar via ics2gcal extension proceeds. However, I am getting an error - "Can't fetch ical file". Not sure if this extension is able to import this way or if there is actually a bug or issue.

Version 90.0.4427.5 (Official Build) dev (x86_64)
Mac Os 11.2.1

**Comment by fmeum** [comment]
Not all download links will work, e.g. if they play some tricks with JavaScript and are not "real" links. 

If you have a non-personalized example link for me, I could take a look.

**Comment by smnjhull** [comment]
Hi there,

Thanks for the quick reply. Unfortunately, I do not currently have a "non-personalized" example. The site I had the issue with is an appointment booking page that requires login. ( [https://mycarecompass.lifelabs.com](https://mycarecompass.lifelabs.com) ) If I come across something in the future I will forward it. I understand that many developers "play tricks" with JS and understand that this is an issue.

Thanks
